import org.gradle.nativeplatform.platform.internal.DefaultNativePlatform

plugins {
    id 'java'
    id 'org.springframework.boot' version '4.0.2'
    id 'io.spring.dependency-management' version '1.1.7'
    id 'io.qameta.allure' version '2.11.2'
    id 'io.freefair.lombok' version '8.6'

}

group = 'ru.kuzya'
version = '0.0.1-SNAPSHOT'
description = 'QAExtensions'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}
allure {
    version = '2.24.0'
    autoconfigure = true
    aspectjweaver = true

    useJUnit5 {
        version = '2.24.0'
    }
}
repositories {
    mavenCentral()
}



dependencies {
    implementation 'org.springframework.boot:spring-boot-starter'
    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
    testImplementation "io.qameta.allure:allure-junit5:2.26.0"

    testImplementation 'io.rest-assured:rest-assured:4.5.1'
    implementation 'io.qameta.allure:allure-rest-assured:2.26.0'

    implementation("com.fasterxml.jackson.datatype:jackson-datatype-jsr310:2.15.3")
    implementation("com.fasterxml.jackson.core:jackson-databind:2.15.3")

    compileOnly 'org.projectlombok:lombok:1.18.30'
    annotationProcessor 'org.projectlombok:lombok:1.18.30'

    // Mockito для моков
    testImplementation 'org.mockito:mockito-core:5.11.0'
    testImplementation 'org.mockito:mockito-junit-jupiter:5.11.0'

    // Для inline моков (если используете)
    testImplementation 'org.mockito:mockito-inline:5.2.0'
}

tasks.named('test') {
    useJUnitPlatform()
    testLogging {
        events "passed", "skipped", "failed"
    }
}


task rerunTests(type: Exec) {
    def testFilePath = "${project.projectDir}/src/test/resources/FailedTests.txt"
    def os = DefaultNativePlatform.currentOperatingSystem;
    println "Checking for test file at: $testFilePath"

    def terminal = os.isWindows() ? "cmd" : "bash"
    def commandKey = os.isWindows() ? "/c" : "-c"
    if (new File(testFilePath).exists()) {
        def testFileContent = new File(testFilePath).text.trim()
        if (!testFileContent.isEmpty()) {
            if (os.isWindows()) {
                commandLine 'cmd', '/c', "gradlew.bat clean test $testFileContent"
            } else {
                commandLine 'bash', '-c', "./gradlew clean test $testFileContent"
            }
        } else {
            commandLine terminal, commandKey, "echo test file does not exist"
        }
    } else {
        commandLine terminal, commandKey, "echo test file does not exist"
    }
    println "Tests rerun completed"
}

